# Generated by Django 4.2.14 on 2024-08-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_date', '-reservation_time']},
        ),
    ]
