# Generated by Django 4.2.14 on 2024-08-28 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_entry_type', models.CharField(choices=[('Starter', 'Starter'), ('Main', 'Main'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks')], max_length=10)),
                ('menu_entry_name', models.CharField(max_length=50)),
                ('menu_entry_description', models.TextField(max_length=100)),
                ('menu_entry_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('menu_entry_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
