# Generated by Django 4.2.14 on 2024-08-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['menu_entry_type']},
        ),
    ]
